language: python
python:
  - "2.7"
  - "3.3" 
  - "3.4"

install: 
  - sudo pip install conda
  - sudo conda init
  - deps='pip numpy matplotlib pandas'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - "pip install ."

script:
  - python -m unittest discover tests

notifications:
  email:
    recipients:
      - adamjdanger+kdx@gmail.com
    on_success: always
    on_failure: always